spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    password:  ${SPRING_DATASOURCE_USERNAME}
    username:  ${SPRING_DATASOURCE_USERNAME}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

server.port: 8094